//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatosDINARDAP.ServiceReferenceDINARDAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", ConfigurationName="ServiceReferenceDINARDAP.IInteroperador")]
    public interface IInteroperador {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DatosDINARDAP.ServiceReferenceDINARDAP.getFichaGeneralResponse getFichaGeneral(DatosDINARDAP.ServiceReferenceDINARDAP.getFichaGeneral request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9340.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/")]
    public partial class fichaGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoPaqueteField;
        
        private institucion[] institucionesField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoPaquete {
            get {
                return this.codigoPaqueteField;
            }
            set {
                this.codigoPaqueteField = value;
                this.RaisePropertyChanged("codigoPaquete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instituciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public institucion[] instituciones {
            get {
                return this.institucionesField;
            }
            set {
                this.institucionesField = value;
                this.RaisePropertyChanged("instituciones");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9340.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/")]
    public partial class institucion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private registro[] datosPrincipalesField;
        
        private item[] detalleField;
        
        private string mensajeField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("registros", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public registro[] datosPrincipales {
            get {
                return this.datosPrincipalesField;
            }
            set {
                this.datosPrincipalesField = value;
                this.RaisePropertyChanged("datosPrincipales");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public item[] detalle {
            get {
                return this.detalleField;
            }
            set {
                this.detalleField = value;
                this.RaisePropertyChanged("detalle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9340.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/")]
    public partial class registro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campoField;
        
        private string codigoField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
                this.RaisePropertyChanged("campo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9340.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/")]
    public partial class item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private registro[] registrosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("registros", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public registro[] registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFichaGeneral", WrapperNamespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", IsWrapped=true)]
    public partial class getFichaGeneral {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroIdentificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoPaquete;
        
        public getFichaGeneral() {
        }
        
        public getFichaGeneral(string numeroIdentificacion, string codigoPaquete) {
            this.numeroIdentificacion = numeroIdentificacion;
            this.codigoPaquete = codigoPaquete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFichaGeneralResponse", WrapperNamespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", IsWrapped=true)]
    public partial class getFichaGeneralResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DatosDINARDAP.ServiceReferenceDINARDAP.fichaGeneral @return;
        
        public getFichaGeneralResponse() {
        }
        
        public getFichaGeneralResponse(DatosDINARDAP.ServiceReferenceDINARDAP.fichaGeneral @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInteroperadorChannel : DatosDINARDAP.ServiceReferenceDINARDAP.IInteroperador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InteroperadorClient : System.ServiceModel.ClientBase<DatosDINARDAP.ServiceReferenceDINARDAP.IInteroperador>, DatosDINARDAP.ServiceReferenceDINARDAP.IInteroperador {
        
        public InteroperadorClient() {
        }
        
        public InteroperadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InteroperadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InteroperadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InteroperadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DatosDINARDAP.ServiceReferenceDINARDAP.getFichaGeneralResponse DatosDINARDAP.ServiceReferenceDINARDAP.IInteroperador.getFichaGeneral(DatosDINARDAP.ServiceReferenceDINARDAP.getFichaGeneral request) {
            return base.Channel.getFichaGeneral(request);
        }
        
        public DatosDINARDAP.ServiceReferenceDINARDAP.fichaGeneral getFichaGeneral(string numeroIdentificacion, string codigoPaquete) {
            DatosDINARDAP.ServiceReferenceDINARDAP.getFichaGeneral inValue = new DatosDINARDAP.ServiceReferenceDINARDAP.getFichaGeneral();
            inValue.numeroIdentificacion = numeroIdentificacion;
            inValue.codigoPaquete = codigoPaquete;
            DatosDINARDAP.ServiceReferenceDINARDAP.getFichaGeneralResponse retVal = ((DatosDINARDAP.ServiceReferenceDINARDAP.IInteroperador)(this)).getFichaGeneral(inValue);
            return retVal.@return;
        }
    }
}
